name: Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout do código
        uses: actions/checkout@v6

      # 2. Configuração do Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # 3. Build
      - name: Build
        run: |
          echo "Iniciando Build..."
          python -m compileall .
          echo "Build concluído com sucesso!"
      
      # 4. Security
      - name: Instalar ferramentas de segurança
        run: |
          pip install -r requirements.txt

      - name: Bandit - SAST
        run: |
          bandit -r .

      - name: pip-audit - SCA
        run: |
          pip-audit

      # 5. Test
      - name: Test
        run: |
          echo "Executando testes automatizados..."
          python -m unittest discover -s tests -v

      # 6. Deploy
      - name: Deploy
        run: |
          echo "Deploy realizado com sucesso!"